#!/usr/bin/env python3
"""Generate SQL updates for CarBrands logos from PNG files.

Default behavior:
- Reads PNG files from ./Assets/Logos (relative to this file)
- Writes SQL to ./UpdateLogos.sql
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


NAME_MAP: dict[str, str] = {
    "bmw": "BMW",
    "mercedes": "Mercedes-Benz",
    "audi": "Audi",
    "volkswagen": "Volkswagen",
    "porsche": "Porsche",
    "opel": "Opel",
    "toyota": "Toyota",
    "honda": "Honda",
    "nissan": "Nissan",
    "mazda": "Mazda",
    "subaru": "Subaru",
    "mitsubishi": "Mitsubishi",
    "suzuki": "Suzuki",
    "lexus": "Lexus",
    "hyundai": "Hyundai",
    "kia": "Kia",
}


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Generate SQL updates for car brand logos.")
    parser.add_argument("--database-name", default="SpareParts", help="Target database name")
    parser.add_argument(
        "--logos-folder",
        default=str(script_dir / "Assets" / "Logos"),
        help="Folder containing PNG logo files",
    )
    parser.add_argument(
        "--output-file",
        default=str(script_dir / "UpdateLogos.sql"),
        help="Output SQL file path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    logos_folder = Path(args.logos_folder)
    if not logos_folder.exists():
        print(f"ERROR: Logos folder not found: {logos_folder}")
        return 1

    logos = sorted(logos_folder.glob("*.png"), key=lambda p: p.name.lower())
    if not logos:
        print(f"ERROR: No PNG files found in: {logos_folder}")
        return 1

    output_file = Path(args.output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines: list[str] = [
        f"USE [{args.database_name}];",
        "GO",
        "",
        "SET NOCOUNT ON;",
        "GO",
        "",
        "BEGIN TRAN;",
        "GO",
        "",
        f"-- Generated by update_logos.py on {generated_at}",
        f"-- Source folder: {logos_folder}",
        "",
    ]

    processed = 0
    skipped = 0

    for logo in logos:
        key = logo.stem.lower()
        brand_name = NAME_MAP.get(key)
        if not brand_name:
            print(f"WARNING: No CarBrands.Name mapping for file '{logo.name}'; skipping.")
            skipped += 1
            continue

        hex_str = "0x" + logo.read_bytes().hex().upper()
        escaped_brand_name = brand_name.replace("'", "''")

        lines.extend(
            [
                f"-- {logo.name} -> {brand_name}",
                "UPDATE CarBrands",
                f"SET    LogoData     = {hex_str},",
                "       LogoMimeType = 'image/png',",
                "       ModifiedAt   = SYSUTCDATETIME()",
                f"WHERE  Name         = '{escaped_brand_name}';",
                "",
                "IF @@ROWCOUNT = 0",
                f"    PRINT 'WARNING: Brand not found: {escaped_brand_name}';",
                "GO",
                "",
            ]
        )

        processed += 1
        print(f"[OK] {logo.name} -> {brand_name}")

    lines.extend(["COMMIT TRAN;", "GO", ""])
    output_file.write_text("\n".join(lines), encoding="utf-8")

    print()
    print(f"Done. Processed: {processed}, Skipped: {skipped}")
    print(f"Output SQL: {output_file}")
    print("Execute the SQL file in SSMS/Azure Data Studio to apply logo updates.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
