# ============================================================
#  UpdateLogos.ps1
#  Run from the solution root:
#    powershell -ExecutionPolicy Bypass -File UpdateLogos.ps1
#
#  Reads every PNG in src\SpareParts.Desktop.Wpf\Assets\Logos\
#  and generates a SQL script that UPDATEs the CarBrands.LogoData
#  column for each matching brand name.
#
#  Output: UpdateLogos.sql  (in same folder as this script)
# ============================================================

$logosFolder = Join-Path $PSScriptRoot "src\SpareParts.Desktop.Wpf\Assets\Logos"
$outputFile  = Join-Path $PSScriptRoot "UpdateLogos.sql"

if (-not (Test-Path $logosFolder)) {
    Write-Error "Logos folder not found: $logosFolder"
    exit 1
}

# Map filename (without extension, lowercase) → CarBrands.Name in DB
$nameMap = @{
    "bmw"         = "BMW"
    "mercedes"    = "Mercedes-Benz"
    "audi"        = "Audi"
    "volkswagen"  = "Volkswagen"
    "porsche"     = "Porsche"
    "opel"        = "Opel"
    "toyota"      = "Toyota"
    "honda"       = "Honda"
    "nissan"      = "Nissan"
    "mazda"       = "Mazda"
    "subaru"      = "Subaru"
    "mitsubishi"  = "Mitsubishi"
    "suzuki"      = "Suzuki"
    "lexus"       = "Lexus"
    "hyundai"     = "Hyundai"
    "kia"         = "Kia"
}

$lines = @()
$lines += "USE SparePartsDb;"
$lines += "GO"
$lines += ""
$lines += "-- Generated by UpdateLogos.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
$lines += "-- Updates CarBrands.LogoData with binary content of each PNG file."
$lines += ""

$count = 0

Get-ChildItem -Path $logosFolder -Filter "*.png" | ForEach-Object {
    $file     = $_
    $key      = $file.BaseName.ToLower()
    $brandName = $nameMap[$key]

    if (-not $brandName) {
        Write-Warning "No DB mapping for file: $($file.Name) — skipping"
        return
    }

    # Read bytes and convert to SQL hex literal  0x...
    $bytes   = [System.IO.File]::ReadAllBytes($file.FullName)
    $hexStr  = "0x" + ($bytes | ForEach-Object { $_.ToString("X2") }) -join ""

    $lines += "-- $($file.Name)  →  [$brandName]"
    $lines += "UPDATE CarBrands"
    $lines += "SET    LogoData     = $hexStr,"
    $lines += "       LogoMimeType = 'image/png',"
    $lines += "       ModifiedAt   = SYSUTCDATETIME()"
    $lines += "WHERE  Name         = '$brandName';"
    $lines += "GO"
    $lines += ""

    $count++
    Write-Host "  ✓  $($file.Name)  →  $brandName  ($($bytes.Length) bytes)"
}

$lines | Set-Content -Path $outputFile -Encoding UTF8

Write-Host ""
Write-Host "Done. $count logo(s) processed."
Write-Host "Output: $outputFile"
Write-Host "Run UpdateLogos.sql in SSMS to apply."
