# ============================================================
#  UpdateLogos.ps1
#
#  Generates a SQL script that updates CarBrands.LogoData and
#  CarBrands.LogoMimeType from PNG files in Assets/Logos.
#
#  Examples:
#    # From anywhere
#    pwsh -File src/SpareParts.Desktop.Wpf/UpdateLogos.ps1
#
#    # Custom DB name/output file
#    pwsh -File src/SpareParts.Desktop.Wpf/UpdateLogos.ps1 \
#      -DatabaseName SparePartsDb \
#      -OutputFile ./tmp/UpdateLogos.sql
# ============================================================

[CmdletBinding()]
param(
    [string]$DatabaseName = "SparePartsDb",
    [string]$LogosFolder = (Join-Path $PSScriptRoot "Assets/Logos"),
    [string]$OutputFile = (Join-Path $PSScriptRoot "UpdateLogos.sql")
)

if (-not (Test-Path $LogosFolder)) {
    Write-Error "Logos folder not found: $LogosFolder"
    exit 1
}

# Map filename (without extension, lowercase) -> CarBrands.Name in DB
$nameMap = @{
    "bmw"         = "BMW"
    "mercedes"    = "Mercedes-Benz"
    "audi"        = "Audi"
    "volkswagen"  = "Volkswagen"
    "porsche"     = "Porsche"
    "opel"        = "Opel"
    "toyota"      = "Toyota"
    "honda"       = "Honda"
    "nissan"      = "Nissan"
    "mazda"       = "Mazda"
    "subaru"      = "Subaru"
    "mitsubishi"  = "Mitsubishi"
    "suzuki"      = "Suzuki"
    "lexus"       = "Lexus"
    "hyundai"     = "Hyundai"
    "kia"         = "Kia"
}

$logos = Get-ChildItem -Path $LogosFolder -Filter "*.png" | Sort-Object Name
if ($logos.Count -eq 0) {
    Write-Error "No PNG files found in: $LogosFolder"
    exit 1
}

$outDir = Split-Path -Parent $OutputFile
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$lines = @()
$lines += "USE [$DatabaseName];"
$lines += "GO"
$lines += ""
$lines += "SET NOCOUNT ON;"
$lines += "GO"
$lines += ""
$lines += "BEGIN TRAN;"
$lines += "GO"
$lines += ""
$lines += "-- Generated by UpdateLogos.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$lines += "-- Source folder: $LogosFolder"
$lines += ""

$processed = 0
$skipped = 0

foreach ($file in $logos) {
    $key = $file.BaseName.ToLowerInvariant()
    $brandName = $nameMap[$key]

    if (-not $brandName) {
        Write-Warning "No CarBrands.Name mapping for file '$($file.Name)'; skipping."
        $skipped++
        continue
    }

    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $hexStr = "0x" + (($bytes | ForEach-Object { $_.ToString("X2") }) -join "")
    $escapedBrandName = $brandName.Replace("'", "''")

    $lines += "-- $($file.Name) -> $brandName ($($bytes.Length) bytes)"
    $lines += "UPDATE CarBrands"
    $lines += "SET    LogoData     = $hexStr,"
    $lines += "       LogoMimeType = 'image/png',"
    $lines += "       ModifiedAt   = SYSUTCDATETIME()"
    $lines += "WHERE  Name         = '$escapedBrandName';"
    $lines += ""
    $lines += "IF @@ROWCOUNT = 0"
    $lines += "    PRINT 'WARNING: Brand not found: $escapedBrandName';"
    $lines += "GO"
    $lines += ""

    Write-Host "  [OK] $($file.Name) -> $brandName ($($bytes.Length) bytes)"
    $processed++
}

$lines += "COMMIT TRAN;"
$lines += "GO"

$lines | Set-Content -Path $OutputFile -Encoding UTF8

Write-Host ""
Write-Host "Done. Processed: $processed, Skipped: $skipped"
Write-Host "Output SQL: $OutputFile"
Write-Host "Execute the SQL file in SSMS/Azure Data Studio to apply logo updates."
