<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Desktop.Interfaces\SpareParts.Desktop.Interfaces.csproj" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Domain\SpareParts.Domain.csproj" />
  </ItemGroup>

</Project>
