namespace SpareParts.Desktop.Wpf
{
    public enum AppScreen
    {
        HomePage,
        Accounting,
        ManualJournal,
        Quotes,
        CustomerAging,
        SupplierAging,
        CarSelection,
        PartSelection,
        Pos,
        PartPurchases,
        Purchases,
        UsedCarWholesale,
        PurchaseHistory,
        StockArrivalTheater,
        RepairPrepBoard,
        StockManagement,
        DeadStockResurrection,
        GrowthLab,
        PartPassport,
        PartCompatibility,
        BarcodeMode,
        ReportBuilder,
        WhatsAppInbox,
        BusinessAssistant,
        ArExperience,
        Reorder,
        ExpiryAlerts,
        Loyalty,
        Warranty,
        Shipments,
        ActivityLog,
        BillingSubscription
    }
}
