-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.AppConstants
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'BaseCurrencyCode', N'LBP', N'Application base currency code used for totals and conversions.', '2026-04-02T13:28:26.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'BrandRegionOrder', N'German,Japanese,Korean', N'Display order for car brand region groups.', '2026-04-02T13:18:45.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'CounterCurrencyCode', N'USD', N'Application counter/default transaction currency code.', '2026-04-02T13:28:26.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'DefaultCounterRate', N'1', N'Fallback counter/base rate when no currency mapping exists.', '2026-04-02T13:18:45.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'DefaultCurrencyCode', N'USD', N'Fallback invoice currency code.', '2026-04-02T13:18:45.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'DefaultSalesTransactionTypeName', N'Sales', N'Default transaction type used when creating invoices.', '2026-04-02T13:18:45.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'DisplayCurrencyCode', N'USD', N'Application display currency code used by screens for money totals.', '2026-05-25T08:17:28.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'ExcelImportProfile.accounttypes', N'{"TargetKey":"accounttypes","Mappings":{"type_key":"Prop1","label":"ReportCategory"}}', N'Excel import profile for AccountTypes.', '2026-04-22T08:30:02.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'ExcelImportProfile.dbo.accountingaccounttypes', N'{"TargetKey":"dbo.AccountingAccountTypes","Mappings":{}}', N'Excel import profile for dbo.AccountingAccountTypes.', '2026-04-24T06:36:38.0000000');
INSERT INTO [dbo].[AppConstants] ([Key], [Value], [Description], [UpdatedAt]) VALUES (N'ExcelImportProfile.dbo.suppliers', N'{"TargetKey":"dbo.Suppliers","Mappings":{}}', N'Excel import profile for dbo.Suppliers.', '2026-04-24T07:09:16.0000000');
