-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.Brands
-- Redacted columns: CreatedByUserId, ModifiedByUserId
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
SET IDENTITY_INSERT [dbo].[Brands] ON;
GO
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (1, N'OEM', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (2, N'Bosch', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (3, N'NGK', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (4, N'Monroe', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (5, N'Bremboo', 1, '2026-03-16T07:43:45.5725072', '2026-03-24T09:00:19.5533333', NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (6, N'Denso', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (7, N'Gates', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (8, N'Mann-Filter', 1, '2026-03-16T07:43:45.5725072', NULL, NULL, NULL);
INSERT INTO [dbo].[Brands] ([Id], [Name], [IsActive], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (10, N'Densoo', 1, '2026-03-23T15:00:00.5433333', NULL, NULL, NULL);
GO
SET IDENTITY_INSERT [dbo].[Brands] OFF;
GO
