-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.Categories
-- Redacted columns: CreatedByUserId, ModifiedByUserId
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
SET IDENTITY_INSERT [dbo].[Categories] ON;
GO
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (1, N'Engine', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (2, N'Transmission', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (3, N'Brakes', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (4, N'Suspension', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (5, N'Electrical', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (6, N'Body & Exterior', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (7, N'Filters', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (8, N'Oils & Fluids', NULL, '2026-03-16T07:43:45.5644883', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (20, N'Cooling & Heating', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (21, N'Doors', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (22, N'Drivetrain', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (23, N'Exhaust System', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (24, N'Fuel System', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (25, N'Glass & Mirrors', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (26, N'Interior', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (27, N'Lighting', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (28, N'Safety', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (29, N'Steering', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentId], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId]) VALUES (30, N'Wheels & Tires', NULL, '2026-05-28T12:24:51.0000000', NULL, NULL, NULL);
GO
SET IDENTITY_INSERT [dbo].[Categories] OFF;
GO
