-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.Warehouses
-- Redacted columns: Address, CreatedByUserId, ModifiedByUserId
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
SET IDENTITY_INSERT [dbo].[Warehouses] ON;
GO
INSERT INTO [dbo].[Warehouses] ([Id], [Name], [Address], [IsMain], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId], [Barcode]) VALUES (1, N'Main Warehouse - Zahle', NULL, 1, '2026-03-16T07:43:45.5497156', NULL, NULL, NULL, N'WH-1');
INSERT INTO [dbo].[Warehouses] ([Id], [Name], [Address], [IsMain], [CreatedAt], [ModifiedAt], [CreatedByUserId], [ModifiedByUserId], [Barcode]) VALUES (2, N'Beirut', NULL, 0, '2026-03-25T15:15:17.0200000', NULL, NULL, NULL, N'WH-2');
GO
SET IDENTITY_INSERT [dbo].[Warehouses] OFF;
GO
