-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.Location
-- Redacted columns: CreatedByUserId, ModifiedByUserId
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
SET IDENTITY_INSERT [dbo].[Location] ON;
GO
INSERT INTO [dbo].[Location] ([LocationID], [Name], [ShippingFees], [ShippingFeesCurrencyCode], [CreatedAt], [CreatedByUserId], [ModifiedAt], [ModifiedByUserId]) VALUES (1, N'Edmonton', 120.00, N'USD', '2026-04-14T08:14:55.0000000', NULL, NULL, NULL);
INSERT INTO [dbo].[Location] ([LocationID], [Name], [ShippingFees], [ShippingFeesCurrencyCode], [CreatedAt], [CreatedByUserId], [ModifiedAt], [ModifiedByUserId]) VALUES (2, N'Calgary', 200.00, N'USD', '2026-04-14T08:15:08.0000000', NULL, NULL, NULL);
GO
SET IDENTITY_INSERT [dbo].[Location] OFF;
GO
