-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Source table: dbo.Locations
-- Redacted columns: CreatedByUserId, ModifiedByUserId
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
SET IDENTITY_INSERT [dbo].[Locations] ON;
GO
GO
SET IDENTITY_INSERT [dbo].[Locations] OFF;
GO
