<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Domain\SpareParts.Domain.csproj" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>
</Project>
