<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="BusinessRules\**" />
    <Content Remove="BusinessRules\**" />
    <EmbeddedResource Remove="BusinessRules\**" />
    <None Remove="BusinessRules\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Infrastructure.Interfaces\SpareParts.Infrastructure.Interfaces.csproj" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Domain\SpareParts.Domain.csproj" />
    <ProjectReference Include="..\SpareParts.Infrastructure\SpareParts.Infrastructure.csproj" />
  </ItemGroup>
</Project>
