<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Infrastructure.Interfaces\SpareParts.Infrastructure.Interfaces.csproj" />
    <PackageReference Include="BCrypt.Lite" Version="1.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpareParts.Domain\SpareParts.Domain.csproj" />
    <ProjectReference Include="..\SpareParts.Infrastructure\SpareParts.Infrastructure.csproj" />
  </ItemGroup>
</Project>
