-- Generated by scripts/export-git-safe-sql-snapshot.ps1
-- Apply after creating the SparePartsDb schema. Run from this directory with sqlcmd mode enabled.
:on error exit
:r .\data\001-dbo.AppConstants.sql
:r .\data\010-dbo.Brands.sql
:r .\data\020-dbo.CarBrands.sql
:r .\data\030-dbo.CarModels.sql
:r .\data\040-dbo.Categories.sql
:r .\data\050-dbo.CurrencyRates.sql
:r .\data\060-dbo.Warehouses.sql
:r .\data\070-dbo.Location.sql
:r .\data\080-dbo.Locations.sql
:r .\data\090-dbo.UsedCars.sql
:r .\data\100-dbo.Parts.sql
:r .\data\110-dbo.Stock.sql
:r .\data\120-dbo.StockMovements.sql
