using SpareParts.Domain.Cars;
using SpareParts.Domain.Genealogy;
using SpareParts.Domain.Marketplace;
using SpareParts.Infrastructure.Services;

namespace SpareParts.Api.Notifications;

/// <summary>
/// The Intake &amp; Teardown Agent — the first agent in the shop's automated "team."
/// The owner's only manual step is logging a purchased used car as received. This service
/// then, without further input:
///   1. Builds a teardown/parts plan for the vehicle (make/model/year).
///   2. Creates a draft part listing for every suggested part, linked back to the used car.
///   3. Logs a genealogy event per part so its origin is traceable.
///   4. Marks the used car processed so it is never re-run.
/// Downstream agents (pricing, listing/marketing, sales) pick up from these draft parts.
/// </summary>
public sealed class IntakeTeardownAgentHostedService : BackgroundService
{
    private static readonly TimeSpan PollInterval = TimeSpan.FromSeconds(30);

    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<IntakeTeardownAgentHostedService> _logger;

    public IntakeTeardownAgentHostedService(
        IServiceScopeFactory scopeFactory,
        ILogger<IntakeTeardownAgentHostedService> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await RunOnceAsync(stoppingToken);

        using var timer = new PeriodicTimer(PollInterval);
        try
        {
            while (await timer.WaitForNextTickAsync(stoppingToken))
            {
                await RunOnceAsync(stoppingToken);
            }
        }
        catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
        {
        }
    }

    private Task RunOnceAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var scope = _scopeFactory.CreateScope();
            var usedCarsService = scope.ServiceProvider.GetRequiredService<UsedCarsService>();
            var carCrushService = scope.ServiceProvider.GetRequiredService<CarCrushService>();
            var genealogyService = scope.ServiceProvider.GetRequiredService<PartGenealogyService>();

            var pending = usedCarsService.GetPendingTeardownCars().ToList();

            foreach (var car in pending)
            {
                if (cancellationToken.IsCancellationRequested) break;
                ProcessCar(usedCarsService, carCrushService, genealogyService, car);
            }
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Intake & Teardown Agent tick failed.");
        }

        return Task.CompletedTask;
    }

    private void ProcessCar(
        UsedCarsService usedCarsService,
        CarCrushService carCrushService,
        PartGenealogyService genealogyService,
        PendingTeardownCarDto car)
    {
        try
        {
            var request = new CarCrushRequest
            {
                VehicleMake = car.Make,
                VehicleModel = car.Model,
                VehicleYear = car.ModelYear
            };

            var plan = carCrushService.Generate(request);
            var selectedPartNames = plan.Suggestions.Select(s => s.PartName).ToList();

            // Attribute the automated records to the owner who logged the purchase, since the
            // whole point of this agent is that no second person ever has to touch the workflow.
            var actorUserId = car.CreatedByUserId ?? 0;

            var createdPartIds = carCrushService.CreateDraftListings(
                request,
                selectedPartNames,
                actorUserId,
                car.Id);

            foreach (var partId in createdPartIds)
            {
                genealogyService.AddEvent(
                    new AddGenealogyEventRequest
                    {
                        PartId = partId,
                        EventType = GenealogyEventType.Dismantled,
                        Description =
                            $"Auto-generated by the Intake & Teardown Agent from the teardown plan for {plan.VehicleDescription} (Used Car #{car.Id}).",
                        ActorName = "Intake & Teardown Agent",
                        TransactionRef = $"UC-{car.Id}",
                        OccurredAt = DateTime.UtcNow
                    },
                    actorUserId);
            }

            usedCarsService.MarkTeardownPlanGenerated(car.Id, createdPartIds.Count);

            _logger.LogInformation(
                "Intake & Teardown Agent: generated {PartCount} draft parts for used car #{UsedCarId} ({VehicleDescription}).",
                createdPartIds.Count,
                car.Id,
                plan.VehicleDescription);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Intake & Teardown Agent failed to process used car #{UsedCarId}.", car.Id);
        }
    }
}
