<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SpareParts.Application\SpareParts.Application.csproj" />
    <ProjectReference Include="..\..\src\SpareParts.Api\SpareParts.Api.csproj" />
    <ProjectReference Include="..\..\src\SpareParts.Infrastructure.Interfaces\SpareParts.Infrastructure.Interfaces.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SpareParts.Infrastructure\SpareParts.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SpareParts.Domain\SpareParts.Domain.csproj" />
    <ProjectReference Include="..\..\src\SpareParts.Desktop.Helpers\SpareParts.Desktop.Helpers.csproj" />
  </ItemGroup>
</Project>
